version: '3.3'

networks:
  ros:
    driver: bridge

services:
  # ROS MASTER (ROSCORE)
  rosmaster:
    image: ros:melodic-ros-core
    command: "roscore"
    networks:
      - ros
    restart: always

  # # # HEIFU Simulation
  simulation:
    build:
      context: ./SimulationDocker
      args:
        GITHASH: ${TODAY}
    image: heifu_simulation:latest
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://rosmaster:11311"
    tty: true
    command: "roslaunch simulation_bringup heifu_simulation.launch argVehicle:='SimpleSim' argLaunchGazeboGUI:=false argOutputIP:='wpManager' argOutputPort:='14550' --wait"
    # command: "sim_vehicle.py -v ArduCopter -m '--out wpManager:14550'"


  # Waypoints Manager
  wpManager:
    build:
      context: ./ControlDocker
      args:
        GITHASH: ${TODAY} #git log --pretty=format:'%h' -n 1)
    image: heifu:latest
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://rosmaster:11311"
    command: "roslaunch heifu-bringup heifu_bringup.launch argSimulation:=true --wait"
    #command: "roslaunch mavros apm.launch argNamespace:='heifu0' fcu_url:='udp://:14550@' --wait"